name: Test DIRTY Ghidra's inference ability

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  test-inference:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        python-version: ["3.10", "3.11"]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup

      - name: Install huggingface-cli
        run: pip install huggingface_hub[cli]

      - name: Cache model files
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/model-dl
          key: hf-model-dl

      - name: Download model files
        run: huggingface-cli download --repo-type model ejschwartz/dirty-ghidra --local-dir $MODEL_DL_DIR && cp -R $MODEL_DL_DIR/data1 $GITHUB_WORKSPACE/dirty/data1
        env:
          MODEL_DL_DIR: ${{ runner.temp }}/model-dl

      - name: Run DIRTY inference
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless projects MyProject -import /bin/ls -postScript $GITHUB_WORKSPACE/scripts/DIRTY_infer.py $(pwd)/infer_success.txt
          test -f infer_success.txt